spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 2002040111Vu
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update        # hoặc create nếu muốn reset bảng mỗi lần chạy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

    defer-datasource-initialization: true   # 🧩 Giúp Spring Boot không chạy data.sql trước khi Hibernate tạo bảng

  # ⚙️ Bắt Spring Boot load file data.sql sau khi Hibernate tạo bảng
  sql:
    init:
      mode: always

  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  port: 8080
